// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PhotoScavengerHunt.Migrations
{
    [DbContext(typeof(PhotoScavengerHuntDbContext))]
    [Migration("20251007113935_AddAuthorIdToTasks")]
    partial class AddAuthorIdToTasks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PhotoScavengerHunt.Features.Photos.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("PhotoSubmissionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PhotoSubmissionId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("PhotoScavengerHunt.Features.Photos.PhotoSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Votes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Photos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PhotoUrl = "https://example.com/photo1.jpg",
                            TaskId = 1,
                            UserId = 1,
                            Votes = 5
                        },
                        new
                        {
                            Id = 2,
                            PhotoUrl = "https://example.com/photo2.jpg",
                            TaskId = 2,
                            UserId = 2,
                            Votes = 3
                        });
                });

            modelBuilder.Entity("PhotoScavengerHunt.Features.Tasks.HuntTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 0,
                            Deadline = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Red car",
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 0,
                            Deadline = new DateTime(2025, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Blue mailbox",
                            Status = 0
                        });
                });

            modelBuilder.Entity("PhotoScavengerHunt.Features.Users.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRegistered")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 20,
                            Email = "",
                            IsRegistered = false,
                            Name = "Ieva",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = 2,
                            Age = 35,
                            Email = "",
                            IsRegistered = false,
                            Name = "Kristina",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = 3,
                            Age = 40,
                            Email = "",
                            IsRegistered = false,
                            Name = "Ausra",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = 4,
                            Age = 61,
                            Email = "",
                            IsRegistered = false,
                            Name = "Ula",
                            PasswordHash = ""
                        });
                });

            modelBuilder.Entity("PhotoScavengerHunt.Features.Photos.Comment", b =>
                {
                    b.HasOne("PhotoScavengerHunt.Features.Photos.PhotoSubmission", null)
                        .WithMany("Comments")
                        .HasForeignKey("PhotoSubmissionId");
                });

            modelBuilder.Entity("PhotoScavengerHunt.Features.Photos.PhotoSubmission", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
