// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PhotoScavengerHunt.Migrations
{
    [DbContext(typeof(PhotoScavengerHuntDbContext))]
    [Migration("20260323164045_FixSqliteDefaultValue")]
    partial class FixSqliteDefaultValue
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("HuntTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TimerSeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Red car"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 0,
                            CreatedAt = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Blue mailbox"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Clock"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Reflection in water or glass"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 0,
                            CreatedAt = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bench with a view"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 0,
                            CreatedAt = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fire hydrant"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Something with wheels (not a car)"
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 0,
                            CreatedAt = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Something perfectly symmetrical"
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tree with colorful leaves"
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 0,
                            CreatedAt = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Animal or pet (no humans visible)"
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Flower growing in an unexpected place"
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 0,
                            CreatedAt = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cloud that looks like something"
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Interesting rock or stone"
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 0,
                            CreatedAt = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Door with a vibrant color"
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Park"
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 0,
                            CreatedAt = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Interesting street art or mural"
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Building with more than 10 floors"
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 0,
                            CreatedAt = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Statue"
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Street sign with an interesting name"
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 0,
                            CreatedAt = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Warning or caution sign"
                        },
                        new
                        {
                            Id = 21,
                            AuthorId = 0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Advertisement with an animal"
                        },
                        new
                        {
                            Id = 22,
                            AuthorId = 0,
                            CreatedAt = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sign in a language other than your native one"
                        },
                        new
                        {
                            Id = 23,
                            AuthorId = 0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bicycle with a basket"
                        },
                        new
                        {
                            Id = 24,
                            AuthorId = 0,
                            CreatedAt = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Vehicle with a funny bumper sticker"
                        },
                        new
                        {
                            Id = 25,
                            AuthorId = 0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Electric vehicle or charging station"
                        },
                        new
                        {
                            Id = 26,
                            AuthorId = 0,
                            CreatedAt = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Public transportation (bus, train, tram)"
                        },
                        new
                        {
                            Id = 27,
                            AuthorId = 0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "House number that adds up to 10"
                        },
                        new
                        {
                            Id = 28,
                            AuthorId = 0,
                            CreatedAt = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Something with stripes"
                        },
                        new
                        {
                            Id = 29,
                            AuthorId = 0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Three items of the same color in one photo"
                        },
                        new
                        {
                            Id = 30,
                            AuthorId = 0,
                            CreatedAt = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Perfect circle in nature or architecture"
                        },
                        new
                        {
                            Id = 31,
                            AuthorId = 0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Coffee shop"
                        },
                        new
                        {
                            Id = 32,
                            AuthorId = 0,
                            CreatedAt = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Something yellow you can eat"
                        },
                        new
                        {
                            Id = 33,
                            AuthorId = 0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ice cream shop"
                        },
                        new
                        {
                            Id = 34,
                            AuthorId = 0,
                            CreatedAt = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bakery"
                        },
                        new
                        {
                            Id = 38,
                            AuthorId = 0,
                            CreatedAt = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Flag flying in the wind"
                        },
                        new
                        {
                            Id = 40,
                            AuthorId = 0,
                            CreatedAt = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Rainbow"
                        });
                });

            modelBuilder.Entity("PhotoScavengerHunt.Features.Challenges.Challenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JoinCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxParticipants")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SubmissionEndsAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("VotingEndsAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("WinnerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Challenges");
                });

            modelBuilder.Entity("PhotoScavengerHunt.Features.Challenges.ChallengeParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChallengeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId");

                    b.HasIndex("UserId");

                    b.ToTable("ChallengeParticipants");
                });

            modelBuilder.Entity("PhotoScavengerHunt.Features.Challenges.ChallengeTask", b =>
                {
                    b.Property<int>("ChallengeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaskId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("TEXT");

                    b.HasKey("ChallengeId", "TaskId");

                    b.HasIndex("TaskId");

                    b.ToTable("ChallengeTasks");
                });

            modelBuilder.Entity("PhotoScavengerHunt.Features.Photos.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PhotoSubmissionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PhotoSubmissionId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("PhotoScavengerHunt.Features.Photos.CommentReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CommentId", "UserId", "Emoji")
                        .IsUnique();

                    b.ToTable("CommentReactions");
                });

            modelBuilder.Entity("PhotoScavengerHunt.Features.Photos.PhotoSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChallengeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TaskId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Votes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Photos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PhotoUrl = "https://example.com/photo1.jpg",
                            TaskId = 1,
                            UserId = 1,
                            Votes = 5
                        },
                        new
                        {
                            Id = 2,
                            PhotoUrl = "https://example.com/photo2.jpg",
                            TaskId = 2,
                            UserId = 2,
                            Votes = 3
                        });
                });

            modelBuilder.Entity("PhotoScavengerHunt.Features.Photos.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PhotoSubmissionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("VotedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("PhotoSubmissionId", "UserId")
                        .IsUnique();

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("PhotoScavengerHunt.Features.Users.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRegistered")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Wins")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "",
                            IsRegistered = false,
                            Name = "Ieva",
                            PasswordHash = "",
                            Wins = 0
                        },
                        new
                        {
                            Id = 2,
                            Email = "",
                            IsRegistered = false,
                            Name = "Kristina",
                            PasswordHash = "",
                            Wins = 0
                        },
                        new
                        {
                            Id = 3,
                            Email = "",
                            IsRegistered = false,
                            Name = "Ausra",
                            PasswordHash = "",
                            Wins = 0
                        },
                        new
                        {
                            Id = 4,
                            Email = "",
                            IsRegistered = false,
                            Name = "Ula",
                            PasswordHash = "",
                            Wins = 0
                        });
                });

            modelBuilder.Entity("PhotoScavengerHunt.Features.Challenges.ChallengeParticipant", b =>
                {
                    b.HasOne("PhotoScavengerHunt.Features.Challenges.Challenge", "Challenge")
                        .WithMany("Participants")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhotoScavengerHunt.Features.Users.UserProfile", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Challenge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PhotoScavengerHunt.Features.Challenges.ChallengeTask", b =>
                {
                    b.HasOne("PhotoScavengerHunt.Features.Challenges.Challenge", "Challenge")
                        .WithMany("ChallengeTasks")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HuntTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Challenge");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("PhotoScavengerHunt.Features.Photos.Comment", b =>
                {
                    b.HasOne("PhotoScavengerHunt.Features.Photos.PhotoSubmission", "PhotoSubmission")
                        .WithMany("Comments")
                        .HasForeignKey("PhotoSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhotoSubmission");
                });

            modelBuilder.Entity("PhotoScavengerHunt.Features.Photos.CommentReaction", b =>
                {
                    b.HasOne("PhotoScavengerHunt.Features.Photos.Comment", "Comment")
                        .WithMany("Reactions")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");
                });

            modelBuilder.Entity("PhotoScavengerHunt.Features.Photos.Vote", b =>
                {
                    b.HasOne("PhotoScavengerHunt.Features.Photos.PhotoSubmission", "PhotoSubmission")
                        .WithMany()
                        .HasForeignKey("PhotoSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhotoScavengerHunt.Features.Users.UserProfile", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PhotoSubmission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PhotoScavengerHunt.Features.Challenges.Challenge", b =>
                {
                    b.Navigation("ChallengeTasks");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("PhotoScavengerHunt.Features.Photos.Comment", b =>
                {
                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("PhotoScavengerHunt.Features.Photos.PhotoSubmission", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
